# -*- coding: utf-8 -*-
"""Adding new Products.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrQRgfLGHcBHSdcgQWs3ne_RY69BRUg-

# **Read Data from JSON**
"""

import json
fd = open("record.json",'r')
r = fd.read()
fd.close()

record = json.loads(r)

"""# **View Records**"""

record

"""# **Fuction to check does Product ID already exist in records**"""

def checkKey(dict, key):
        if key in dict:
            print("\n \nThe Product ID ", product_id, " Already Exist ")
            print("value =", record[product_id])
            quantity = int(input("Enter Quantity: "))
            print("The Old Quantity : ",record[product_id]['Quantity'], "Will be updated with  New Quantity : ", quantity, " entered of Product ID : ", product_id)
            print("\n\n")
            record[product_id]['Quantity'] += quantity
        else:
            return 1

"""# **Add New Item into Inventory**"""

print("Welcome to Inventory Data system \n\nYou can add Product Data into the Records \n")
print("******************************** \n \n")
print("Enter the Number of products you want to add into the Data(Records) ")
num = int(input())
print("Enter the Product Details of " , num , " products")


for i in range(0,num):
  print("Enter the Product " ,i+1," Details ")

  product_id = str(input("Enter Product id: "))
  res = 0
  res = checkKey(record, product_id)
  if (res == 1):
     name = str(input("Enter Name: "))
     price = int(input("Enter Price: "))
     quantity = int(input("Enter Quantity: "))
     category = str(input("Enter Category: "))
     manu_name = str(input("Enter Manufacturer Name: "))
     print("\n********************************* \n")
     record[product_id] = {'Product': product_id, 'Price': price, 'Quantity': quantity , 'Category': category , 'Manufacturer': manu_name}

"""# **Write Data to JSON**"""

js = json.dumps(record)
fd = open("record.json",'w')
fd.write(js)
fd.close()