# -*- coding: utf-8 -*-
"""Purchasing products.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1szj-JTyPEhQLJw1bK8T3QuYfNeQb7CVx

# **Read Inventory**
"""

import json
import time
import uuid

fd = open("record.json",'r')
r = fd.read()
fd.close()

records = json.loads(r)

"""# **Read Sales**"""

fd = open("sales.json",'r')
ja = fd.read()
fd.close()
sales = json.loads(ja)

"""# **View Records**"""

records

"""# **Purchase**

# **Display Inventory**
"""

def view_inventory():
  for i in records:
    print("Product ID : " , i, " -> Product Name : " , records[i]["Product"] ," -> Product Price : " ,records[i]["Price"] )
    print("Product Quantity : " ,records[i]["Quantity"]," -> Product Category : " , records[i]["Category"] ," -> Product Manufacturer : " , records[i]["Manufacturer"] )
    print("\n----------------------------------------------------------------------------------------------------------------------------------------\n")

"""# **Update Inventory Data/Records**"""

def record_update():
  rs = json.dumps(records)
  fd = open("record.json",'w')
  fd.write(rs)
  fd.close()

"""# **Update Sales Data**"""

def sales_update(user_prod_id,user_prod_qn):
  s = uuid.uuid4()
  s=str(s)
  random=s[0:8]

  sales[random] = {'Product ID': user_prod_id ,'Product Name': records[user_prod_id]['Product'], 
                    'Amount': records[user_prod_id]['Price'] * user_prod_qn ,'Quantity':user_prod_qn ,'Time' : time.ctime()}

  #updating sales.json
  ws = json.dumps(sales)
  fd = open("sales.json",'w')
  fd.write(ws)
  fd.close()

"""# **Purchase Function**"""

def purchase():
  user_prod_id = str(input("Enter the Product ID: "))

  if user_prod_id in records :
    print("Product Name : " , records[user_prod_id]['Product'])
  else :
    user_prod_id =str(input("Product ID not found ,\nPlease re-check the product key and enter"))
    
  user_prod_qn = int(input("Enter the Quantity: "))
  if (user_prod_qn > records[user_prod_id]["Quantity"]):
    print("Sorry for Inconvenience , The product your looking for is out of stock")
    print("Please buy some other Products/items")
  
  print("Price: ", records[user_prod_id]['Price'])
  Billing_Amount = records[user_prod_id]['Price'] * user_prod_qn
  print("Billing Amount: ", records[user_prod_id]['Price'] * user_prod_qn)
  records[user_prod_id]['Quantity'] = records[user_prod_id]['Quantity'] - user_prod_qn
  
  #calling Update record fuction 
  record_update()

  #calling update sales fuction
  sales_update(user_prod_id,user_prod_qn)

  print("Purchase Done.")
  return Billing_Amount

"""# **Main Program**"""

print("Welcome to Santhosh BIG Market ")
print("\n ************************\n ")
bill=0
print("\nPlease enter the choice \n")
print("\n1.View Inventory Records \n2.Buy Products \n3.Exit")
choice = int(input())
if  ( choice == 1):
  print('\n----------------------------------\n')

  print("\nItems available in Santhosh BIG Market \n")
  
  print('\n----------------------------------\n')
  view_inventory()
  blah=str(input("\n Do you want to Buy items : \n Y/N  ")).lower()
  if (blah=='y'):
    bill = purchase()
    more = str(input("\n Do you want to buy more Product : y/n \n")).lower()
    if (more =="y"):
      bill += purchase()
      print("Thank you For Purchasing..\n     Visit Again....")

if(choice == 2):
  bla=str(input("\nDo you want to view inventory : y/n \n")).lower()
  if (bla == 'y'):
    view_inventory()
  bill += purchase()
  more = str(input("\n Do you want to buy more Product : y/n \n")).lower()
  if (more =="y"):
    bill += purchase()
    print("Thank you For Purchasing..\n     Visit Again....")

print("Total Bill : " , bill)


print("\nThank You .... Vist Again\n")